/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LAB1;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class Dispatch extends javax.swing.JFrame {
    private PalindromoAir air;
    private Ticket[] asientosCantidad;
    
    public Dispatch(Ticket[] asientosCantidadExternos, PalindromoAir airExterno) {
        asientosCantidad = asientosCantidadExternos;
        air = airExterno;
        
        initComponents();
        
        PasajerosField.setText(air.printPassengers());
        IngresoGeneradoField.setText("$. " + Double.toString(air.income()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PasajerosField = new javax.swing.JTextArea();
        IngresoGeneradoField = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        BotonDespachar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasajerosField.setEditable(false);
        PasajerosField.setBackground(new java.awt.Color(255, 255, 255));
        PasajerosField.setColumns(20);
        PasajerosField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        PasajerosField.setForeground(new java.awt.Color(0, 0, 0));
        PasajerosField.setRows(5);
        PasajerosField.setBorder(null);
        jScrollPane1.setViewportView(PasajerosField);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 450, 120));

        IngresoGeneradoField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        IngresoGeneradoField.setForeground(new java.awt.Color(0, 0, 0));
        IngresoGeneradoField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(IngresoGeneradoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 350, 30));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 60, 60));

        BotonDespachar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonDespachar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDespacharMouseClicked(evt);
            }
        });
        jPanel1.add(BotonDespachar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 200, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LAB1/Dispatch.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal(air.getAsientosCantidad(), this.air);
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonDespacharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDespacharMouseClicked
        air.dispatch();
        
        JOptionPane.showMessageDialog(null, "Vuelo ha sido despachado exitosamente.", "Vuelo Despachado", JOptionPane.INFORMATION_MESSAGE);
        
        MenuPrincipal menuPrincipal = new MenuPrincipal(air.getAsientosCantidad(), this.air);
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonDespacharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dispatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dispatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dispatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dispatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dispatch(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonDespachar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IngresoGeneradoField;
    private javax.swing.JTextArea PasajerosField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
